version: "2.3"

services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ="Europe/Berlin"
      - NTFY_BASE_URL="https://notify.skom-service.de"
      - NTFY_CACHE_FILE="/var/cache/ntfy/cache.db"
      - NTFY_AUTH_FILE="/var/lib/ntfy/auth.db"
      - NTFY_AUTH_DEFAULT_ACCESS="deny-all"
      - NTFY_BEHIND_PROXY=true
      - NTFY_ATTACHMENT_CACHE_DIR="/var/lib/ntfy/attachments"
      - NTFY_ENABLE_LOGIN=true
      - NTFY_UPSTREAM_BASE_URL="https://ntfy.sh"
    volumes:
      - ./cache:/var/cache/ntfy
      - ./db:/var/lib/ntfy/
    ports:
      - 8001:80
    restart: unless-stopped
